apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: django-ingress
  namespace: ns-16
  annotations:
    haproxy-org/ingress.class: haproxy
spec:
  ingressClassName: haproxy
  rules:
  - host: node-16.fergus.host
    http:
      paths:
        - path: /
          backend:
            serviceName: django-service
            servicePort: 8000
        - path: /api/
          backend:
             serviceName: django-service
             servicePort: 8000
        - path: /admin/
          backend:
             serviceName: django-service
             servicePort: 8000
