kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    app: django-container
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30755

